apiVersion: 1

# Política de notificação padrão
# Envia todos os alertas (sem filtro de label) para o contact point de email

policies:
  - orgId: 1
    receiver: Email Alertas
    group_by: [grafana_folder, alertname]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
